### ISSUE TITLE
Simulationcraft crashes everytime I press simulate

### ISSUE THREAD

**Issue by pjohnson9091** [simulationcraft/simc#2891]
It is as the title says, once I press simulate the program stops working and I am required to close it. Everything up until then I am able to do

**Comment by Collisionc** [comment]
Can you copy/paste the simc_gui.txt file that is located in the folder with the program after it crashes?

**Comment by pjohnson9091** [comment]
I can't find the .txt file, but I found the simc_gui.simc file.

**Comment by Collisionc** [comment]
sorry, that's what I meant.

**Comment by pjohnson9091** [comment]
"Sorry, but this was the best way to do this"

### Begin GUI options

item_db_source=local/bcpapi/wowhead
target_error=0
iterations=10000
default_world_lag=0.1
max_time=300
vary_combat_length=0.2
fight_style=Patchwerk
tmi_window_global=6
target_level+=3
target_race=Humanoid
default_skill=1.0
optimal_raid=0
override.bloodlust=1
override.bleeding=1
override.mortal_wounds=1
threads=8
process_priority=Low
statistics_level=1

### End GUI options

### Begin simulateText

deathknight="Azgrelg_Active"
origin="https://us.api.battle.net/wow/character/zuljin/Azgrelg/advanced"
thumbnail="http://us.battle.net/static-render/us/zuljin/2/179613442-avatar.jpg"
level=79
race=orc
role=attack
position=back
professions=mining=26/skinning=27
talents=http://us.battle.net/wow/en/tool/talent-calculator#db!10101..
spec=unholy

# This default action priority list is automatically created based on your character.

# It is a attempt to provide you with a action list that is both simple and practicable,

# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.

# Feel free to edit, adapt and improve it to your own needs.

# SimulationCraft is always looking for updates and improvements to the default action lists.

# Executed before combat begins. Accepts non-harmful actions only.

# Snapshot raid buffed stats before combat begins and pre-potting is done.

actions.precombat=snapshot_stats
actions.precombat+=/raise_dead

# Executed every time the actor is available.

actions=auto_attack
actions+=/arcane_torrent,if=runic_power.deficit>20
actions+=/blood_fury
actions+=/berserking
actions+=/use_item,slot=trinket2
actions+=/outbreak,target_if=!dot.virulent_plague.ticking
actions+=/dark_transformation,if=equipped.137075&cooldown.dark_arbiter.remains>165
actions+=/dark_transformation,if=equipped.137075&!talent.shadow_infusion.enabled&cooldown.dark_arbiter.remains>55
actions+=/dark_transformation,if=equipped.137075&talent.shadow_infusion.enabled&cooldown.dark_arbiter.remains>35
actions+=/dark_transformation,if=equipped.137075&target.time_to_die<cooldown.dark_arbiter.remains-8
actions+=/dark_transformation,if=equipped.137075&cooldown.summon_gargoyle.remains>160
actions+=/dark_transformation,if=equipped.137075&!talent.shadow_infusion.enabled&cooldown.summon_gargoyle.remains>55
actions+=/dark_transformation,if=equipped.137075&talent.shadow_infusion.enabled&cooldown.summon_gargoyle.remains>35
actions+=/dark_transformation,if=equipped.137075&target.time_to_die<cooldown.summon_gargoyle.remains-8
actions+=/dark_transformation,if=!equipped.137075&rune<=3
actions+=/blighted_rune_weapon,if=rune<=3
actions+=/run_action_list,name=valkyr,if=talent.dark_arbiter.enabled&pet.valkyr_battlemaiden.active
actions+=/call_action_list,name=generic

actions.aoe=death_and_decay,if=spell_targets.death_and_decay>=2
actions.aoe+=/epidemic,if=spell_targets.epidemic>4
actions.aoe+=/scourge_strike,if=spell_targets.scourge_strike>=2&(dot.death_and_decay.ticking|dot.defile.ticking)
actions.aoe+=/clawing_shadows,if=spell_targets.clawing_shadows>=2&(dot.death_and_decay.ticking|dot.defile.ticking)
actions.aoe+=/epidemic,if=spell_targets.epidemic>2

actions.castigator=festering_strike,if=debuff.festering_wound.stack<=4&runic_power.deficit>23
actions.castigator+=/death_coil,if=!buff.necrosis.up&talent.necrosis.enabled&rune<=3
actions.castigator+=/scourge_strike,if=buff.necrosis.react&debuff.festering_wound.stack>=3&runic_power.deficit>23
actions.castigator+=/scourge_strike,if=buff.unholy_strength.react&debuff.festering_wound.stack>=3&runic_power.deficit>23
actions.castigator+=/scourge_strike,if=rune>=2&debuff.festering_wound.stack>=3&runic_power.deficit>23
actions.castigator+=/death_coil,if=talent.shadow_infusion.enabled&talent.dark_arbiter.enabled&!buff.dark_transformation.up&cooldown.dark_arbiter.remains>15
actions.castigator+=/death_coil,if=talent.shadow_infusion.enabled&!talent.dark_arbiter.enabled&!buff.dark_transformation.up
actions.castigator+=/death_coil,if=talent.dark_arbiter.enabled&cooldown.dark_arbiter.remains>15
actions.castigator+=/death_coil,if=!talent.shadow_infusion.enabled&!talent.dark_arbiter.enabled

actions.generic=dark_arbiter,if=!equipped.137075&runic_power.deficit<30
actions.generic+=/dark_arbiter,if=equipped.137075&runic_power.deficit<30&cooldown.dark_transformation.remains<2
actions.generic+=/summon_gargoyle,if=!equipped.137075,if=rune<=3
actions.generic+=/summon_gargoyle,if=equipped.137075&cooldown.dark_transformation.remains<10&rune<=3
actions.generic+=/soul_reaper,if=debuff.festering_wound.stack>=7&cooldown.apocalypse.remains<2
actions.generic+=/apocalypse,if=debuff.festering_wound.stack>=7
actions.generic+=/death_coil,if=runic_power.deficit<30
actions.generic+=/death_coil,if=!talent.dark_arbiter.enabled&buff.sudden_doom.up&!buff.necrosis.up&rune<=3
actions.generic+=/death_coil,if=talent.dark_arbiter.enabled&buff.sudden_doom.up&cooldown.dark_arbiter.remains>5&rune<=3
actions.generic+=/festering_strike,if=debuff.festering_wound.stack<7&cooldown.apocalypse.remains<5
actions.generic+=/wait,sec=cooldown.apocalypse.remains,if=cooldown.apocalypse.remains<=1&cooldown.apocalypse.remains
actions.generic+=/soul_reaper,if=debuff.festering_wound.stack>=3
actions.generic+=/festering_strike,if=debuff.soul_reaper.up&!debuff.festering_wound.up
actions.generic+=/scourge_strike,if=debuff.soul_reaper.up&debuff.festering_wound.stack>=1
actions.generic+=/clawing_shadows,if=debuff.soul_reaper.up&debuff.festering_wound.stack>=1
actions.generic+=/defile
actions.generic+=/call_action_list,name=aoe,if=active_enemies>=2
actions.generic+=/call_action_list,name=instructors,if=equipped.132448
actions.generic+=/call_action_list,name=standard,if=!talent.castigator.enabled&!equipped.132448
actions.generic+=/call_action_list,name=castigator,if=talent.castigator.enabled&!equipped.132448

actions.instructors=festering_strike,if=debuff.festering_wound.stack<=4&runic_power.deficit>23
actions.instructors+=/death_coil,if=!buff.necrosis.up&talent.necrosis.enabled&rune<=3
actions.instructors+=/scourge_strike,if=buff.necrosis.react&debuff.festering_wound.stack>=5&runic_power.deficit>29
actions.instructors+=/clawing_shadows,if=buff.necrosis.react&debuff.festering_wound.stack>=5&runic_power.deficit>29
actions.instructors+=/scourge_strike,if=buff.unholy_strength.react&debuff.festering_wound.stack>=5&runic_power.deficit>29
actions.instructors+=/clawing_shadows,if=buff.unholy_strength.react&debuff.festering_wound.stack>=5&runic_power.deficit>29
actions.instructors+=/scourge_strike,if=rune>=2&debuff.festering_wound.stack>=5&runic_power.deficit>29
actions.instructors+=/clawing_shadows,if=rune>=2&debuff.festering_wound.stack>=5&runic_power.deficit>29
actions.instructors+=/death_coil,if=talent.shadow_infusion.enabled&talent.dark_arbiter.enabled&!buff.dark_transformation.up&cooldown.dark_arbiter.remains>15
actions.instructors+=/death_coil,if=talent.shadow_infusion.enabled&!talent.dark_arbiter.enabled&!buff.dark_transformation.up
actions.instructors+=/death_coil,if=talent.dark_arbiter.enabled&cooldown.dark_arbiter.remains>15
actions.instructors+=/death_coil,if=!talent.shadow_infusion.enabled&!talent.dark_arbiter.enabled

actions.standard=festering_strike,if=debuff.festering_wound.stack<=4&runic_power.deficit>23
actions.standard+=/death_coil,if=!buff.necrosis.up&talent.necrosis.enabled&rune<=3
actions.standard+=/scourge_strike,if=buff.necrosis.react&debuff.festering_wound.stack>=1&runic_power.deficit>15
actions.standard+=/clawing_shadows,if=buff.necrosis.react&debuff.festering_wound.stack>=1&runic_power.deficit>15
actions.standard+=/scourge_strike,if=buff.unholy_strength.react&debuff.festering_wound.stack>=1&runic_power.deficit>15
actions.standard+=/clawing_shadows,if=buff.unholy_strength.react&debuff.festering_wound.stack>=1&runic_power.deficit>15
actions.standard+=/scourge_strike,if=rune>=2&debuff.festering_wound.stack>=1&runic_power.deficit>15
actions.standard+=/clawing_shadows,if=rune>=2&debuff.festering_wound.stack>=1&runic_power.deficit>15
actions.standard+=/death_coil,if=talent.shadow_infusion.enabled&talent.dark_arbiter.enabled&!buff.dark_transformation.up&cooldown.dark_arbiter.remains>15
actions.standard+=/death_coil,if=talent.shadow_infusion.enabled&!talent.dark_arbiter.enabled&!buff.dark_transformation.up
actions.standard+=/death_coil,if=talent.dark_arbiter.enabled&cooldown.dark_arbiter.remains>15
actions.standard+=/death_coil,if=!talent.shadow_infusion.enabled&!talent.dark_arbiter.enabled

actions.valkyr=death_coil
actions.valkyr+=/apocalypse,if=debuff.festering_wound.stack=8
actions.valkyr+=/festering_strike,if=debuff.festering_wound.stack<8&cooldown.apocalypse.remains<5
actions.valkyr+=/call_action_list,name=aoe,if=active_enemies>=2
actions.valkyr+=/festering_strike,if=debuff.festering_wound.stack<=3
actions.valkyr+=/scourge_strike,if=debuff.festering_wound.up
actions.valkyr+=/clawing_shadows,if=debuff.festering_wound.up

head=burnished_helm_of_might,id=122263
neck=amulet_of_the_stampede,id=43309
shoulders=shoulderplates_of_the_abolished,id=44352
back=worn_stoneskin_gargoyle_cape,id=122260
chest=burnished_breastplate_of_might,id=122387
tabard=illustrious_guild_tabard,id=69209
wrists=steel_bear_trap_bracers,id=35593
hands=iceencrusted_gauntlets,id=113692,bonus_id=29
waist=rhinotail_girdle,id=39453
legs=iceencrusted_plate_legguards,id=112354,bonus_id=36
feet=boots_of_dominance,id=39466
finger1=ring_of_foul_mojo,id=43178
finger2=executioners_band,id=38218
trinket1=insignia_of_the_scourge,id=40483
trinket2=abacus_of_violent_odds,id=28288
main_hand=ingvars_monolithic_cleaver,id=35576,enchant=rune_of_the_fallen_crusader

# Gear Summary

# gear_ilvl=134.27

# gear_strength=185

# gear_agility=14

# gear_stamina=217

# gear_attack_power=54

# gear_crit_rating=126

# gear_haste_rating=167

# gear_armor=283

### End simulateText

### Begin overrides

# User-specified persistent global and player parameters will be set here.

### End overrides

### Begin final options

### End final options

### END

**Comment by Collisionc** [comment]
Yep, that crashes. I'll see what's going on.

**Comment by navv1234** [comment]
Outbreak looks to have changed somewhat, probably need to slightly rebuild the spell in simc. I'll take a look later today.

EDIT: Nevermind, I'll fix this .. somehow.

**Comment by navv1234** [comment]
This should be fixed in 453cabe7afdd404e37382d04c9f48e103828cb94.

**Comment by pjohnson9091** [comment]
Ok I changed it, but it is still crashing is there anything else that you could think of that I would need to change.

**Comment by Collisionc** [comment]
Did you download a newer version? http://downloads.simulationcraft.org/?C=M;O=D  Top download is newest

**Comment by pjohnson9091** [comment]
that was the issue, at the time that I created this post I had downloaded the newest version that was advertised on the website.
Thank you for the help.
