### ISSUE TITLE
[SV Hunter] Spitting Cobra Damage not matching Live Datas

### ISSUE THREAD

**Issue by Meatwookie** [simulationcraft/simc#3407]
Spitting Cobra Damage is not matching the current live data

https://i.gyazo.com/2ef56508722dc3a852f285bfe6b7930f.png

that is the damage it is doing in SimC 49674f1

however on live servers, the average hit is ~49k and average crit is ~98k

was also without Moknathal Stacks+Flask ingame so 12% ap less
using my own character
+ it should be scaling with haste

```hunter="Aibee"
level=110
race=orc
region=eu
server=tarren_mill
role=
professions=alchemy=9/enchanting=65
talents=3121231
spec=survival
artifact=34:0:0:0:0:1068:1:1070:3:1071:3:1072:3:1073:3:1074:3:1075:3:1076:3:1077:3:1078:3:1079:1:1080:1:1081:1:1082:1:1083:1:1084:1:1338:1:1370:1
# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action lists.
 
# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/food,type=fishbrul_special
actions.precombat+=/summon_pet
# Snapshot raid buffed stats before combat begins and pre-potting is done.
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=old_war
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/dragonsfire_grenade
actions.precombat+=/explosive_trap,if=!talent.dragonsfire_grenade.enabled
actions.precombat+=/harpoon
 
# Executed every time the actor is available.
actions=auto_attack
actions+=/arcane_torrent,if=focus.deficit>=30
actions+=/berserking
actions+=/blood_fury
actions+=/potion,name=old_war,if=buff.aspect_of_the_eagle.remains
actions+=/call_action_list,name=moknathal,if=talent.way_of_the_moknathal.enabled
actions+=/call_action_list,name=nomok,if=!talent.way_of_the_moknathal.enabled
 
actions.moknathal+=/raptor_strike,if=buff.moknathal_tactics.stack<=1
actions.moknathal+=/raptor_strike,if=buff.moknathal_tactics.remains<gcd
actions.moknathal+=/snake_hunter,if=cooldown.mongoose_bite.charges<=0&buff.mongoose_fury.remains>3*gcd
actions.moknathal+=/a_murder_of_crows,if=focus>55-buff.moknathal_tactics.remains*focus.regen&buff.mongoose_fury.stack<4&buff.mongoose_fury.remains>=gcd
actions.moknathal+=/steel_trap,if=buff.mongoose_fury.remains>=gcd&buff.mongoose_fury.stack<4
actions.moknathal+=/caltrops,if=(buff.mongoose_fury.remains>=gcd&buff.mongoose_fury.stack<4&!dot.caltrops.ticking)
actions.moknathal+=/flanking_strike,if=cooldown.mongoose_bite.charges<=0&buff.aspect_of_the_eagle.remains>=gcd&focus>75-buff.moknathal_tactics.remains*focus.regen
actions.moknathal+=/carve,if=equipped.frizzos_fingertrap&focus>65-buff.moknathal_tactics.remains*focus.regen&buff.mongoose_fury.remains>=gcd&dot.lacerate.remains<=3&dot.lacerate.ticking
actions.moknathal+=/lacerate,if=focus>60-buff.moknathal_tactics.remains*focus.regen&buff.mongoose_fury.remains>=gcd&!dot.lacerate.ticking&buff.mongoose_fury.stack<4
actions.moknathal+=/spitting_cobra,if=buff.mongoose_fury.remains>=gcd&buff.mongoose_fury.stack<4
actions.moknathal+=/steel_trap,if=buff.mongoose_fury.remains>=gcd&buff.mongoose_fury.stack<4
actions.moknathal+=/explosive_trap,if=buff.mongoose_fury.remains>=gcd&buff.mongoose_fury.stack<4
actions.moknathal+=/dragonsfire_grenade,if=buff.mongoose_fury.remains>=gcd&buff.mongoose_fury.stack<4
actions.moknathal+=/raptor_strike,if=buff.moknathal_tactics.remains<4&buff.mongoose_fury.stack=6&buff.mongoose_fury.remains>=gcd&cooldown.fury_of_the_eagle.remains<=6
actions.moknathal+=/mongoose_bite,if=buff.aspect_of_the_eagle.up&buff.mongoose_fury.up&buff.moknathal_tactics.stack>=4
actions.moknathal+=/fury_of_the_eagle,if=buff.moknathal_tactics.remains>4&buff.mongoose_fury.stack=6&cooldown.mongoose_bite.charges<=2
actions.moknathal+=/fury_of_the_eagle,if=(buff.moknathal_tactics.remains>4&(buff.mongoose_fury.stack=6&cooldown.mongoose_bite.charges<=0|buff.mongoose_fury.up&buff.mongoose_fury.remains<=2*gcd))
actions.moknathal+=/raptor_strike,if=buff.moknathal_tactics.stack=3
actions.moknathal+=/aspect_of_the_eagle,if=buff.mongoose_fury.up&buff.mongoose_fury.remains>6&cooldown.mongoose_bite.charges>=2
actions.moknathal+=/flanking_strike,if=cooldown.mongoose_bite.charges<=2&buff.mongoose_fury.remains>(1+action.mongoose_bite.charges*gcd)&focus>75-buff.moknathal_tactics.remains*focus.regen
actions.moknathal+=/mongoose_bite,if=buff.mongoose_fury.up&buff.mongoose_fury.remains<cooldown.aspect_of_the_eagle.remains
actions.moknathal+=/a_murder_of_crows,if=focus>55-buff.moknathal_tactics.remains*focus.regen
actions.moknathal+=/spitting_cobra
actions.moknathal+=/steel_trap
actions.moknathal+=/explosive_trap
actions.moknathal+=/caltrops,if=(!dot.caltrops.ticking)
actions.moknathal+=/lacerate,if=(!dot.lacerate.ticking|dot.lacerate.remains<3)
actions.moknathal+=/dragonsfire_grenade
actions.moknathal+=/butchery,if=(charges=3&focus>65-buff.moknathal_tactics.remains*focus.regen)
actions.moknathal+=/mongoose_bite,if=(charges>=2&cooldown.mongoose_bite.remains<=gcd|charges=3)
actions.moknathal+=/butchery,if=focus>65-buff.moknathal_tactics.remains*focus.regen
actions.moknathal+=/flanking_strike,if=focus>75-buff.moknathal_tactics.remains*focus.regen
actions.moknathal+=/raptor_strike,if=focus>75-cooldown.flanking_strike.remains*focus.regen

 
actions.nomok+=/a_murder_of_crows,if=buff.mongoose_fury.stack<4
actions.nomok+=/snake_hunter,if=action.mongoose_bite.charges<=0&buff.mongoose_fury.remains>3*gcd   
actions.nomok+=/steel_trap,if=buff.mongoose_fury.remains>=gcd&buff.mongoose_fury.stack<4
actions.nomok+=/caltrops,if=(buff.mongoose_fury.remains>=gcd&buff.mongoose_fury.stack<4&!dot.caltrops.ticking)
actions.nomok+=/flanking_strike,if=cooldown.mongoose_bite.charges<=0&buff.aspect_of_the_eagle.remains>=gcd
actions.nomok+=/carve,if=equipped.frizzos_fingertrap&buff.mongoose_fury.remains>=gcd&dot.lacerate.remains<=3&dot.lacerate.ticking
actions.nomok+=/lacerate,if=buff.mongoose_fury.remains>=gcd&dot.lacerate.remains<=1&buff.mongoose_fury.stack<4
actions.nomok+=/spitting_cobra,if=buff.mongoose_fury.remains>=gcd&buff.mongoose_fury.stack<4
actions.nomok+=/steel_trap,if=buff.mongoose_fury.remains>=gcd&buff.mongoose_fury.stack<4
actions.nomok+=/explosive_trap,if=buff.mongoose_fury.remains>=gcd&buff.mongoose_fury.stack<4
actions.nomok+=/dragonsfire_grenade,if=buff.mongoose_fury.remains>=gcd&buff.mongoose_fury.stack<4
actions.nomok+=/raptor_strike,if=talent.serpent_sting.enabled&dot.serpent_sting.remains<gcd
actions.nomok+=/mongoose_bite,if=buff.aspect_of_the_eagle.up&buff.mongoose_fury.up
actions.nomok+=/fury_of_the_eagle,if=buff.mongoose_fury.stack=6&cooldown.mongoose_bite.charges<=2
actions.nomok+=/fury_of_the_eagle,if=(buff.mongoose_fury.stack=6&cooldown.mongoose_bite.charges<=0)|(buff.mongoose_fury.up&buff.mongoose_fury.remains<=2*gcd)
actions.nomok+=/aspect_of_the_eagle,if=buff.mongoose_fury.up&buff.mongoose_fury.remains>6&cooldown.mongoose_bite.charges>=2
actions.nomok+=/flanking_strike,if=cooldown.mongoose_bite.charges<2&buff.mongoose_fury.remains>(1+action.mongoose_bite.charges*gcd)
actions.nomok+=/mongoose_bite,if=buff.mongoose_fury.up&buff.mongoose_fury.remains<cooldown.aspect_of_the_eagle.remains
actions.nomok+=/flanking_strike,if=talent.animal_instincts.enabled&cooldown.mongoose_bite.charges<3
actions.nomok+=/a_murder_of_crows
actions.nomok+=/spitting_cobra
actions.nomok+=/steel_trap
actions.nomok+=/explosive_trap
actions.nomok+=/caltrops,if=(!dot.caltrops.ticking)
actions.nomok+=/lacerate,if=(!dot.lacerate.ticking|dot.lacerate.remains<3)
actions.nomok+=/dragonsfire_grenade
actions.nomok+=/butchery,if=(charges=3)
actions.nomok+=/throwing_axes,if=cooldown.throwing_axes.charges=2
actions.nomok+=/mongoose_bite,if=(charges>=2&cooldown.mongoose_bite.remains<=gcd|charges=3)
actions.nomok+=/butchery
actions.nomok+=/throwing_axes
actions.nomok+=/flanking_strike
actions.nomok+=/raptor_strike,if=focus>75-cooldown.flanking_strike.remains*focus.regen


head=,id=137064,bonus_id=3459/3458
neck=,id=139332,enchant_id=5439,bonus_id=1807/1497/3337
shoulder=,id=134169,enchant_id=5881,bonus_id=3474/1522/3337
back=,id=133771,enchant_id=5435,bonus_id=3418/1537/3337
chest=,id=137354,bonus_id=3412/1522/3337
wrist=,id=139222,bonus_id=1805/1487
hands=,id=137333,bonus_id=3509/1522/1813
waist=,id=139212,bonus_id=1805/1502/3337
legs=,id=139216,bonus_id=1805/1487
feet=,id=137034,bonus_id=1811/3458
finger1=,id=134526,enchant_id=5430,bonus_id=3417/41/1527/3337
finger2=,id=139236,enchant_id=5430,bonus_id=1807/1477/3336
trinket1=,id=137419,bonus_id=3414/1517/3336
trinket2=,id=139329,bonus_id=1805/1497/3336
main_hand=,id=128808,bonus_id=728,relic_id=1805:1492:3336/1805:1492:3336/1805:1497:3336,gem_id=137008/139255/139260/0
summon_pet=carrion_bird```

**Comment by nuoHep** [comment]
I've merged an initial implementation of a guardian based snake which now benefits from haste and (I believe at least) has the correct owner ap coefficient.
The ap coefficient matches all ap values I've tested so far (more than in the comment; technically it's closer to 1.41397 though, I rounded it to 1.414). It definitely does not snapshot, though it lags somewhat in updating its stats.

But, it's still not complete and undervalued because it looks like the snake double dips on at least haste & vers.
e.g. at 26303 AP & 3.14% vers it does 39564 per hit which matches 26303 * 1.414 * 1.0314 * 1.0314
at 16.52% haste it has a cast time of ~1.48 which matches 2 / 1.1652 / 1.1652 (and with sephuzs it becomes .95)

I'll do some more testing tomorrow (to see if I can push it lower than .75s cast time and if it double dips on anything else) and think about how to implement all that.

**Comment by nuoHep** [comment]
So I've committed the pocket snake double-dipping off vers & haste. It should be doing considerably more damage now. Though it may be possible that it's double-dipping off something else. Sadly I won't have the time to test it any further for several days at least.

**Comment by Zuliane** [comment]
Spitting_Cobra still does not match live data. In SimC it does not benefit from the 30% damage amplification of aspect_of_the_eagle/aspect_of_the_skylord and the 20% of mongoose_power.

With AotE and Mongoose Power: http://i.imgur.com/6pp6qUH.png
Without AotE and without Mongoose Power: http://i.imgur.com/8LWFW2O.png
Live: https://www.warcraftlogs.com/reports/rtJPyTWV1ahLc2MD#fight=9&type=damage-done&source=13&start=2126236&end=2150411&ability=-194407

On the other hand the spitting_cobra casts in Simc are way to frequent compared to live servers.
I am not sure what the cause is. If you want me to test certain scenarios to get a better understanding of how it behaves, just tell me which one. The problem is not exclusive to Trolls.

SimC: http://i.imgur.com/PmiTeK7.png (5.0 executes)
Live: https://www.warcraftlogs.com/reports/rtJPyTWV1ahLc2MD#fight=9&type=damage-done&source=13&ability=-194407&start=1918787&end=2221529

This is not a one time thing, I observed this over several logs. Gained haste effects are similar.(1x BL, 2x Berserking, same stats)

e: the critical chance increase of AotE seems to be ok, removed that part

**Comment by nuoHep** [comment]
I've committed e8c791df28 (forgot to mention the issue there)
As my spear is not even at 35 traits I can't check if the sneak double-dips on +damage% multipliers in some non-obvious way or not.

Leaving it open until I get 35 in Surv and can test at least the damage multiplier more thoroughly.

**Comment by navv1234** [comment]
Closing, probably fixed by now. If not, reply.
