### ISSUE TITLE
Cannot download Simulationcraft 7.3 ver. / Windows Defender does not accept this

### ISSUE THREAD

**Issue by Logern** [simulationcraft/simc#4019]
If you've read the title, this is my current problem, windows defender - as in my anit virus on the PC im using, is blocking all of SimC atm, both 32 and 64bit versions

Any idea on what to do..? Just download..?

**Comment by ToxicSoul17** [comment]
I also am having the same issue. It says theres a problem, tried downloading it anyway and when I opened up SimulationCraft the Navigation bars up top aren't showing up. 
I used the app 7Z file manager and on the welcome folders and it had an Error when I tired to Test the folder in the 7z app. 
Please help!

**Comment by Xanzara** [comment]
This should have been resolved by updated build process.

**Comment by ToxicSoul17** [comment]
Tried downloading the new files yesterday, uninstalled the previous simcraft and downloaded the new file, still does not show navigation up top.
